var aindaNaoSabemos;
aindaNaoSabemos = 1;
aindaNaoSabemos = true;
aindaNaoSabemos = 'teste';
console.log(aindaNaoSabemos);
var listaIndefinida = [1, true, 'teste1'];
console.log(listaIndefinida);
var qualquerCoisa;
qualquerCoisa = 5;
qualquerCoisa = '';
qualquerCoisa = false;
console.log(qualquerCoisa);
var listaAleatoria = [5, 'texto', true];
console.log(listaAleatoria);
